### ISSUE TITLE
memexec payload

### ISSUE THREAD

**Issue by norey** [wintrmvte/SNOWCRASH#2]
Hello

The `available_payloads` array does not contain `memexec` so it needs to be fixed in order to use that payload.
I also need an example of its usage with the right arguments. E.g. if `elf_args` and `exe_args` are empty, what arguments should I pass?

Thanks

**Comment by l4ckyguy** [comment]
just inspect source. if u can u can =)

**Comment by l4ckyguy** [comment]
u can also inspect logo, for example do extract with c-chef

**Comment by wintrmvte** [comment]
Good point, I will fix this in next commit. Speaking of options, you should specify either `exe_args` or `elf_args` - leaving both empty is pointless, because then nothing is executed.
